CREATE TABLE IF NOT EXISTS games (
  game_id CHAR(5) NOT NULL PRIMARY KEY,
  left_team VARCHAR(80) NOT NULL,
  right_team VARCHAR(80) NOT NULL,
  left_color VARCHAR(7) NOT NULL,
  right_color VARCHAR(7) NOT NULL,
  left_score INT UNSIGNED NOT NULL DEFAULT 0,
  right_score INT UNSIGNED NOT NULL DEFAULT 0,
  left_games INT UNSIGNED NOT NULL DEFAULT 0,
  right_games INT UNSIGNED NOT NULL DEFAULT 0,
  set_number INT UNSIGNED NOT NULL DEFAULT 1,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE EVENT IF NOT EXISTS purge_old_games
  ON SCHEDULE EVERY 1 HOUR
  DO DELETE FROM games WHERE updated_at < (CURRENT_TIMESTAMP - INTERVAL 1 DAY);
